In [1]:
import pandas as pd
import numpy as np

In [2]:
raw_data = pd.read_csv(r"C:\Users\001\OneDrive\Projects\Customer Churn Analysis\Data\Customer_Details.csv")
data = raw_data.copy()
data

,state,account_length,area_code,phone_number,international_plan,voice_mail_plan,number_vmail_messages,total_day_minutes,total_day_calls,total_day_charge,...,total_eve_calls,total_eve_charge,total_night_minutes,total_night_calls,total_night_charge,total_intl_minutes,total_intl_calls,total_intl_charge,number_customer_service_calls,class
0,16,128,415,2845,0,1,25,265.1,110,45.07,...,99,16.78,244.7,91,11.01,10.0,3,2.70,1,0
1,35,107,415,2301,0,1,26,161.6,123,27.47,...,103,16.62,254.4,103,11.45,13.7,3,3.70,1,0
2,31,137,415,1616,0,0,0,243.4,114,41.38,...,110,10.30,162.6,104,7.32,12.2,5,3.29,0,0
3,35,84,408,2510,1,0,0,299.4,71,50.90,...,88,5.26,196.9,89,8.86,6.6,7,1.78,2,0
4,36,75,415,155,1,0,0,166.7,113,28.34,...,122,12.61,186.9,121,8.41,10.1,3,2.73,3,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,11,50,408,2000,0,1,40,235.7,127,40.07,...,126,18.96,297.5,116,13.39,9.9,5,2.67,2,0
4996,49,152,415,394,0,0,0,184.2,90,31.31,...,73,21.83,213.6,113,9.61,14.7,2,3.97,3,1
4997,7,61,415,313,0,0,0,140.6,89,23.90,...,128,14.69,212.4,97,9.56,13.6,4,3.67,1,0
4998,7,109,510,3471,0,0,0,188.8,67,32.10,...,92,14.59,224.4,89,10.10,8.5,6,2.30,0,0
4999,46,86,415,2412,0,1,34,129.4,102,22.00,...,104,22.70,154.8,100,6.97,9.3,16,2.51,0,0

In [3]:
inputs = data.iloc[:,:-1]
target = data.iloc[:,-1]

In [4]:
inputs

,state,account_length,area_code,phone_number,international_plan,voice_mail_plan,number_vmail_messages,total_day_minutes,total_day_calls,total_day_charge,total_eve_minutes,total_eve_calls,total_eve_charge,total_night_minutes,total_night_calls,total_night_charge,total_intl_minutes,total_intl_calls,total_intl_charge,number_customer_service_calls
0,16,128,415,2845,0,1,25,265.1,110,45.07,197.4,99,16.78,244.7,91,11.01,10.0,3,2.70,1
1,35,107,415,2301,0,1,26,161.6,123,27.47,195.5,103,16.62,254.4,103,11.45,13.7,3,3.70,1
2,31,137,415,1616,0,0,0,243.4,114,41.38,121.2,110,10.30,162.6,104,7.32,12.2,5,3.29,0
3,35,84,408,2510,1,0,0,299.4,71,50.90,61.9,88,5.26,196.9,89,8.86,6.6,7,1.78,2
4,36,75,415,155,1,0,0,166.7,113,28.34,148.3,122,12.61,186.9,121,8.41,10.1,3,2.73,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,11,50,408,2000,0,1,40,235.7,127,40.07,223.0,126,18.96,297.5,116,13.39,9.9,5,2.67,2
4996,49,152,415,394,0,0,0,184.2,90,31.31,256.8,73,21.83,213.6,113,9.61,14.7,2,3.97,3
4997,7,61,415,313,0,0,0,140.6,89,23.90,172.8,128,14.69,212.4,97,9.56,13.6,4,3.67,1
4998,7,109,510,3471,0,0,0,188.8,67,32.10,171.7,92,14.59,224.4,89,10.10,8.5,6,2.30,0
4999,46,86,415,2412,0,1,34,129.4,102,22.00,267.1,104,22.70,154.8,100,6.97,9.3,16,2.51,0

In [10]:
target.value_counts()

0    4293
1     707
Name: class, dtype: int64

its looks like the targets arent balanced so i need to balance the targets variable
## balancing the targets

In [11]:
target

0       0
1       0
2       0
3       0
4       0
       ..
4995    0
4996    1
4997    0
4998    0
4999    0
Name: class, Length: 5000, dtype: int64

In [14]:
#steps is created to balance the data
number_of_churn = int(np.sum(target)) #calculates the total number of churn by sum them up
zero_count = 0
row_to_remove = [] #list to append rows to be removed from data

for i in range(inputs.shape[0]):
  if target[i] == 0:
    zero_count += 1
    if zero_count > number_of_churn:
      row_to_remove.append(i)


balanced_inputs = np.delete(inputs, row_to_remove, axis=0)
balanced_targets = np.delete(target, row_to_remove, axis=0)

ValueError: Shape of passed values is (1414, 20), indices imply (5000, 20)

In [13]:
balanced_targets.sum()/balanced_targets.shape

NameError: name 'balanced_targets' is not defined

In [ ]:
shuffle_indices = np.arange(balanced_targets.shape[0])
np.random.shuffle(shuffle_indices)

balanced_shuffle_inputs = balanced_inputs[shuffle_indices]
balanced_shuffle_targets = balanced_targets[shuffle_indices]

In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
scale = StandardScaler()
scale.fit(balanced_shuffle_inputs)

In [ ]:
balanced_scaled_inputs = scale.transform(balanced_shuffle_inputs)
balanced_scaled_inputs

In [ ]:
balanced_scaled_inputs.shape

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(balanced_scaled_inputs, balanced_shuffle_targets, train_size=0.8, random_state=350)

In [ ]:
x_train.shape, y_train.shape

In [ ]:
x_test.shape, y_test.shape

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

In [ ]:
result = LogisticRegression()

In [ ]:
result.fit(x_train, y_train)

In [ ]:
result.score(x_train, y_train)

In [ ]:
pd.options.display.max_columns = None
pd.options.display.max_rows = None

In [ ]:
model_output = result.predict(x_train)
model_output

finding the **intercept** and **co-efficient**

In [ ]:
result.intercept_

In [ ]:
result.coef_

In [ ]:
inputs.columns.values

In [ ]:
feature_names = inputs.columns.values

In [ ]:
feature_importance = pd.DataFrame(columns=['featurs Name'], data = feature_names)
feature_importance['Coefficient'] = np.transpose(result.coef_)
feature_importance

In [ ]:
feature_importance.index = feature_importance.index + 1

feature_importance.loc[0] = ['Intercept', result.intercept_[0]]

feature_importance.sort_index(inplace=True)

feature_importance

**interpreting the co-efficient**

In [ ]:
feature_importance['Odds_ratio'] = np.exp(feature_importance.Coefficient)

In [ ]:
feature_importance

In [ ]:
feature_importance.sort_values('Odds_ratio', ascending=False)

its clear from the cooefficient that Gender, DeviceProtection, SeniorCitixen, OnlineBackup, Partner are less important in the model as they are farther away from 0 which means it wont really matter if thses variables are taken out

## testing the model

In [ ]:
result.score(x_test, y_test)

In [ ]:
predictions = result.predict(x_test)

In [ ]:
predicted_probability = result.predict_proba(x_test)
predicted_probability[:,1]

In [ ]:
x_test

In [ ]:
predicted = pd.DataFrame(columns = inputs.columns.values, data = x_test)
predicted['Probability'] = predicted_probability[:,1]
predicted['churn'] = predictions
predicted